source 'https://github.com/CocoaPods/Specs.git'

target 'HaidoraThemeKit_Example', :exclusive => true do
  pod "HaidoraThemeKit", :path => "../"
end

target 'HaidoraThemeKit_Tests', :exclusive => true do
  pod "HaidoraThemeKit", :path => "../"

  
end
